#sdk: c:/projects/rhodes
#sdk: ../rhodes

#capabilities:
#  - push

sdkversion: 3.2.0
name: store
version: 1.0
vendor: tautechnologies
rho_app_id: com.tautechnologies.store
build: debug
applog: rholog.txt
bbver: 6.0

wm:
  #sdk: "MC3000c50b (ARMV4I)"

iphone:
  configuration: Debug
  sdk: iphoneos10.2
  emulator: 4.0.1
  #provisionprofile:
  #codesignidentity:
  #entitlements:
  #http_connection_domains: ["tau-store-server.herokuapp.com"]
  BundleIdentifier: com.tautechnologies.store
  info_plist_data:
    NSAppTransportSecurity:
      NSAllowsArbitraryLoads: true


#extensions: ["json", "rhoconnect-client", "applePush"]
extensions: ["json", "rhoconnect-client"]

android:
  version: 2.2
  emulator: android-2.2

wp:
  productid: '1aa73f88-4d47-4f94-acdd-ab9301d45a2a'

symbian:
  uid: '0xea92ef73'

#bb:
#  ignore_bb6_suffix: 1
